### ISSUE TITLE
please build manylinux wheels

### ISSUE THREAD

**Issue by costela** [ndparker/rjsmin#14]
Hey,

It would be really nice to have a [manylinux](https://github.com/pypa/manylinux) version on pypi. This would probably also solve (or at least alleviate) #7.

Cheers

**Comment by ndparker** [comment]
Heh. just while releasing a new version.

I'll check out if I can integrate the docker container quickly.

**Comment by ndparker** [comment]
BTDT. Please check it out, if they actually work: https://pypi.org/project/rjsmin/#files

**Comment by costela** [comment]
Thanks for the quick answer! (got lucky with the release timing)
My tests are admittedly a bit limited, but the wheel _seem_ to be working fine.

**Comment by ndparker** [comment]
Close enough, I guess. Nobody complained :-) -> Closing now.
