### ISSUE TITLE
option --without-c-extensions not recognized

### ISSUE THREAD

**Issue by Hand-some** [ndparker/rjsmin#15]
Hey,

I am having trouble installing rjsmin under the option "--without-c-extensions" and this is how it feeds me back

Installing collected packages: rjsmin
  Running setup.py install for rjsmin ... error
    Complete output from command c:\users\gary\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Gary\\AppData\\Local\\Temp\\pip-install-4trtsdxb\\rjsmin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Gary\AppData\Local\Temp\pip-record-lo8x_60k\install-record.txt --single-version-externally-managed --compile --without-c-extensions:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --without-c-extensions not recognized

However, I am able to install rcssmin module successfully under the option  "--without-c-extensions".

**Comment by ndparker** [comment]
Yes, the option is no more. That's one of the reasons this version got a bigger bump.

**Comment by ndparker** [comment]
(rcssmin will change, too. Rather sooner than later)

**Comment by Hand-some** [comment]
Well, thanks.
(It seems that I have to install Microsoft Visual C++ 14 so that I am able to install django-compressor)

**Comment by Hand-some** [comment]
Oooooo thanks.
I have just tried the strategy you mentioned half an hour ago and it works very well.
Thanks again.

**Comment by ndparker** [comment]
:+1:

**Comment by rjviercech** [comment]
pip install django_compressor==1 fix the problem, of course you have to install msvc ++ 14.0

**Comment by rjviercech** [comment]
`pip install django_compressor==1` fix the problem, of course you have to install msvc ++ 14.0
