### ISSUE TITLE
pypi releases don't match tags in this repository

### ISSUE THREAD

**Issue by dvzrv** [ndparker/rjsmin#19]
Hi! I'm packaging python-rjsmin for Arch Linux.
The [releases on pypi](https://pypi.org/project/rjsmin/#history) don't match the [tags in this repository](https://github.com/ndparker/rjsmin/releases).

To fend off supply chain attacks, it would be great to keep the tags and releases in sync. Thank you!

**Comment by ndparker** [comment]
Hi, I've pushed the missing 1.1.0 tag, sorry for that.

The older ones are not even in github, but somewhere else. This part of the history is simply missing here on github. Not much I can do about that :-)

Cheers,
