### ISSUE TITLE
Add linux aarch64 wheel support

### ISSUE THREAD

**Issue by odidev** [ndparker/rjsmin#24]
Problem
---------
On aarch64, ‘pip install rjsmin’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install rjsmin’ should download the wheels from pypi.

@ndparker Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by ndparker** [comment]
Fixed.
