### ISSUE TITLE
Not compatible with AlpineJS

### ISSUE THREAD

**Issue by XChikuX** [ndparker/rjsmin#29]
Hi **rjsmin** team,

I use FastAPI to send html content to my frontend.

Before I do so, I minify it with rjsmin.

alpinejs uses the '@' symbol quite often and it is very likely to come right after an html tag.

Eg.

```
<button
@click="open = true" 
hx-get="/web/form.html"
hx-trigger="click"
hx-target="#info"
class="signup-button font-semibold px-6 py-4 text-2xl rounded-full hover:scale-110 transition-transform ease-in-out duration-500"
>
```

In the above example `@click="open = true"` gets appended to the word *button* without any spacing. This behaviour is consistent across all my files. And although I don't think it's a bug.

It is a much needed enhancement to avoid this spacing issue.

**Comment by ndparker** [comment]
Hi,

let me understand this correctly: Are you trying to minify HTML code with rjsmin? That cannot work.

Cheers,

**Comment by XChikuX** [comment]
Actually, your code does really well with html, css and js files :)

There are just a few hiccups here and there.

**Comment by ndparker** [comment]
I'm afraid I can't support minifying anything other than javascript with rjsmin.
