### ISSUE TITLE
Incompatible with python 3.5

### ISSUE THREAD

**Issue by svenstaro** [ndparker/rjsmin#5]
I get this on python 3.5 during installation:

    OSError: Need at max python 3.4 (vs. 3.5.0)

**Comment by ashep** [comment]
+1
Please fix ASAP and update PyPi's version.
Thank you!

**Comment by ndparker** [comment]
Thanks for the reminder. Will release soon(ish).

**Comment by ashep** [comment]
@ndparker thank you!
