### ISSUE TITLE
Installation breaks with new setuptools

### ISSUE THREAD

**Issue by joostrijneveld** [ndparker/rjsmin#9]
This is the same issue as rcssmin is suffering from, documented at https://github.com/ndparker/rcssmin/issues/6

**Comment by mogosselin** [comment]
People that are after a quick solution, you can downgrade setuptools using pip with these 2 commands:

- pip uninstall setuptools
- pip install -I setuptools==28.6.1

**Comment by joostrijneveld** [comment]
This has been resolved in setuptools 28.7.1.
